opt_in_rules:
- force_unwrapping
- force_cast
- file_header
- function_parameter_count
disabled_rules:
- line_length
- colon
- trailing_whitespace
- unused_closure_parameter
- shorthand_operator
- redundant_void_return
- implicit_optional_initialization
- type_body_length
- superfluous_disable_command
- redundant_string_enum_value
- function_body_length
- cyclomatic_complexity
- identifier_name
- type_name
- weak_delegate
- class_delegate_protocol
- file_length
- large_tuple
- empty_enum_arguments
- comment_spacing
- legacy_random
- inclusive_language
- void_function_in_ternary

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

force_unwrapping: error
force_cast: error
vertical_whitespace: error
opening_brace: error
comma: error
force_try: error
